### ISSUE TITLE
Problem I got when add it to the self-hold mattermost server

### ISSUE THREAD

**Issue by yuexiongHNU** [mattermost/mattermost-plugin-autotranslate#1]
### I download the plugin source code and compile successfuly, but when I add it to matttermost server, I can't run it successful, I get errors below:

> {"level":"error","ts":1539943585.877963,"caller":"app/plugin.go:70","msg":"Unable to activate plugin","plugin_id":"autotranslate","error":"unable to start plugin: autotranslate: Must have AWS Access Key ID","errorVerbose":"Must have AWS Access Key ID\nunable to start plugin: autotranslate\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/plugin/environment.go:211\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:68\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:141\ngithub.com/mattermost/mattermost-server/app.(*App).InvokeConfigListeners\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:138\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:50\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:206\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/plugin.go:183\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:131\ngithub.com/mattermost/mattermost-server/web.(*Handler).ServeHTTP\n\t<autogenerated>:1\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP\n\t<autogenerated>:1\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}
{"level":"error","ts":1539943588.0861664,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"autotranslate","error":"plugin not found: autotranslate"}

![image](https://user-images.githubusercontent.com/14088768/47214977-3b858880-d3d2-11e8-9286-53709439b64f.png)

### I add ak and sk of aws correctly, but it also got the  error "Must have AWS Access Key ID", Can somebody help me?

**Comment by amyblais** [comment]
Hi @yuexiongHNU,

According to step 3 in the instructions, you would also need an AWS Access Key ID: https://github.com/mattermost/mattermost-plugin-autotranslate#installation. Perhaps this documentation will help: https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys.

**Comment by saturninoabril** [comment]
Thanks for your report @yuexiongHNU!
In addition to above, can you confirm that the AWS translate is working in your CLI using your access & secret keys?  You may confirm that your setup is working following this AWS docs - https://docs.aws.amazon.com/translate/latest/dg/setting-up.html

**Comment by saturninoabril** [comment]
@yuexiongHNU I'm closing this now. Feel free to reopen or create a new issue.
