### ISSUE TITLE
Where can I get the released plugin

### ISSUE THREAD

**Issue by yuexiongHNU** [mattermost/mattermost-plugin-autotranslate#2]
By the way,  where can I get released plugin?

**Comment by Taffer** [comment]
Yes please, this looks interesting.

**Comment by icelander** [comment]
Hi there,

You can find releases for this plugin at https://github.com/mattermost/mattermost-plugin-autotranslate/releases/

**Comment by Taffer** [comment]
Excellent, thanks! 👍

**Comment by saturninoabril** [comment]
@yuexiongHNU @Taffer Thanks for your interest, please let us know your experience with it.

Closing this now.

**Comment by poVoq** [comment]
@Taffer @icelander any chance for a new release with the recent changes? It seems like there have been a few nice ones. Thanks!

**Comment by saturninoabril** [comment]
Yes, I'm planning to cut a new one, will just need to run some verification.  Will keep you posted.
