### ISSUE TITLE
docs(readme): Currently not compatible with Mattermost?

### ISSUE THREAD

**Issue by Splaktar** [mattermost/mattermost-plugin-autotranslate#8]
From the [README](https://github.com/mattermost/mattermost-plugin-autotranslate#installation):

### Installation
> Requires Mattermost 5.4 or higher (Currently not compatible with Mattermost as there's minor change requested to plugin system.)

I'm specifically curious about this line:
> Currently not compatible with Mattermost as there's minor change requested to plugin system.

Is this accurate?

**Comment by saturninoabril** [comment]
Oh nice catch! That particular line on readme was submitted before v5.3.  Will update that.
Thanks!

It should only be "Requires Mattermost 5.4 or higher".

I'm closing this unless you experienced something that makes above not correct.
